# Generated by Django 2.0.6 on 2018-06-07 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='estadistica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=30)),
                ('Apodo', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='partida',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teg.usuario'),
        ),
        migrations.AddField(
            model_name='estadistica',
            name='usuario_est',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teg.usuario'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teg.partida'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teg.usuario'),
        ),
    ]
